"""
Redline stage Lambda — issue #188 (mock pipeline: materialize the output
document object).

Mock-pipeline scope (issue #59 / #210): the real redline generator
(scripts/redline_docx_writer.py, wired by #83 behind the #62 eval gate) is
NOT invoked here. In the mock pipeline the "redline" for the eiaa playbook is
a pre-baked, clearly-SYNTHETIC tracked-changes .docx staged in the outputs
bucket at `mock-fixtures/eiaa/pre-baked-redline.docx` (seeded by the CDK
BucketDeployment in pipeline-stack.ts, generated by
scripts/gen_mock_eiaa_redline_fixture.py). This stage's only job is to COPY
that fixture, server-side, into the review's own per-review output prefix so
`GET /api/reviews/{id}/output` has a real object to presign.

Why this stage (not persist) owns the copy: the copy touches ONLY the outputs
data class (read `mock-fixtures/*`, write `outputs/*`, same bucket + CMK), so
it belongs on the redline stage's `pipelineOutputsRole` -- the one pipeline
role granted outputs-bucket read/write. persist runs on the DynamoDB
bookkeeping role and holds no S3 grant (data-class isolation, issue #70 AC B);
it writes the terminal `reviews` row instead.

Coupling to the reviews-row write (issue #188 decision): on a successful copy
this stage stamps `output_object_written: true` onto the pointer-only event.
The persist stage records `output_s3_key` onto the reviews row ONLY when that
flag is set, so the download affordance is never shown for an object that was
never materialized.

Fail-closed: a copy failure re-raises, so the state machine's shared
`.addCatch` routes the review to ERROR (a visible, recoverable terminal
state) rather than letting persist advertise a download that would 404.

POINTER-ONLY PAYLOAD RULE (issue #19): the event carries S3 keys only -- no
document bytes ever pass through Step Functions history. The .docx bytes move
entirely server-side via S3 CopyObject.

Input event shape (pointer-only; from the mock review stage):
  {
    "review_id": "...",
    "decision": "REQUEST_CHANGE" | "MANUAL_REVIEW_REQUIRED",
    "output_s3_key": null | "outputs/<review_id>/out.docx",
    "pre_baked_source_key": "mock-fixtures/eiaa/pre-baked-redline.docx",
    ...
  }

Output: the input event, plus `output_object_written: true` when a copy was
performed (absent otherwise).

Environment variables:
  OUTPUTS_BUCKET   S3 bucket holding both mock-fixtures/* and outputs/*
"""

import os
from typing import Any

import boto3

OUTPUTS_BUCKET = os.environ.get("OUTPUTS_BUCKET", "")


def _s3():
    return boto3.client("s3")


def handler(event: dict[str, Any], _context: Any = None) -> dict[str, Any]:
    """Step Functions task entry point for the (mock) redline stage."""
    output_s3_key = event.get("output_s3_key")
    source_key = event.get("pre_baked_source_key")

    # MANUAL_REVIEW_REQUIRED (nda / unknown playbook) carries no output_s3_key
    # and no pre-baked source -- nothing to materialize, pass straight through.
    if not output_s3_key or not source_key:
        return event

    if not OUTPUTS_BUCKET:
        # Misconfiguration: fail closed so the review lands in ERROR rather
        # than silently proceeding to persist with no object written.
        raise RuntimeError("OUTPUTS_BUCKET is not configured for the redline stage.")

    # Server-side copy within the outputs bucket: mock-fixtures/... -> the
    # review's own outputs/<review_id>/ prefix. No SSE header is set; S3
    # applies the outputs bucket's default SSE-KMS CMK to the destination
    # object (same CMK as the source, same data class).
    _s3().copy_object(
        Bucket=OUTPUTS_BUCKET,
        Key=output_s3_key,
        CopySource={"Bucket": OUTPUTS_BUCKET, "Key": source_key},
    )

    # Signal to the persist stage that the object now exists, so it is safe to
    # record output_s3_key onto the reviews row (issue #188 coupling).
    event["output_object_written"] = True
    return event
