/**
 * ct-chip — status pill (CTDS foundation, issue #385).
 *
 * Shadow DOM leaf (§5.2 of docs/frontend-design-system.md): the only
 * meaningful content is the slotted label, which stays in light DOM so
 * @testing-library and screen readers see it directly — nothing this
 * component renders internally (besides the optional decorative dot) is
 * ever something a test needs to assert on.
 *
 * Visual treatment mirrors the existing `.ct-chip` / `.ct-chip--*` classes in
 * frontend/src/styles/app.css (pill shape, status bg/fg pairs from
 * frontend/src/styles/tokens.css) — this component supersedes those classes;
 * every usage is migrated in this same issue.
 *
 * Reactive properties use Lit's `static properties` block rather than the
 * `@property` decorator, and registration goes through `defineOnce`
 * (../define.ts) rather than `@customElement` — both keep this file
 * decorator-free, which sidesteps any interaction with tsconfig's
 * `useDefineForClassFields`. The `declare` fields below tell TypeScript the
 * properties exist (accessors are generated by Lit from `static properties`)
 * without emitting real class-field initializers that would shadow those
 * accessors.
 */
import { LitElement, css, html, nothing } from 'lit';
import { defineOnce } from '../define';

export type CtChipVariant = 'ok' | 'warn' | 'danger' | 'info' | 'muted';

const TAG = 'ct-chip';

export class CtChip extends LitElement {
  static properties = {
    variant: { type: String, reflect: true },
    dot: { type: Boolean, reflect: true },
  };

  declare variant: CtChipVariant;
  declare dot: boolean;

  constructor() {
    super();
    this.variant = 'muted';
    this.dot = false;
  }

  static styles = css`
    :host {
      display: inline-flex;
      align-items: center;
      gap: 0.35rem;
      font-size: 0.78rem;
      font-weight: 600;
      line-height: 1.4;
      padding: 0.15rem 0.6rem;
      border-radius: 999px;
      border: 1px solid var(--ct-neutral);
      background: var(--ct-neutral-bg);
      color: var(--ct-neutral);
      white-space: nowrap;
    }
    :host([variant='ok']) {
      border-color: var(--ct-ok);
      background: var(--ct-ok-bg);
      color: var(--ct-ok);
    }
    :host([variant='warn']) {
      border-color: var(--ct-warn);
      background: var(--ct-warn-bg);
      color: var(--ct-warn);
    }
    :host([variant='danger']) {
      border-color: var(--ct-danger);
      background: var(--ct-danger-bg);
      color: var(--ct-danger);
    }
    :host([variant='info']) {
      border-color: var(--ct-accent);
      background: var(--ct-info-bg);
      color: var(--ct-accent);
    }
    :host([variant='muted']) {
      border-color: var(--ct-border);
      background: var(--ct-neutral-bg);
      color: var(--ct-text-muted);
    }
    .ct-chip__dot {
      width: 6px;
      height: 6px;
      flex: none;
      border-radius: 999px;
      background: currentColor;
    }
  `;

  render() {
    return html`${this.dot ? html`<span class="ct-chip__dot" aria-hidden="true"></span>` : nothing}<slot></slot>`;
  }
}

defineOnce(TAG, CtChip);
