/**
 * aws-exports.ts — Amplify configuration.
 *
 * IMPORTANT: In a deployed environment this file is GENERATED by
 * `python3 scripts/generate_aws_exports.py` from CDK stack outputs after
 * `cdk deploy` — see that script's module docstring for the full CDK-outputs
 * key contract. This committed version is a placeholder stub so that:
 *   (a) the TypeScript compiler and Vite can type-check and build the app,
 *   (b) CI can run `vite build` without real AWS credentials.
 *
 * For local development against a real deploy:
 *   1. Run `cdk deploy --context env=dev` to deploy the dev stack.
 *   2. Run `python3 scripts/generate_aws_exports.py --outputs <cdk-outputs.json>
 *      --output frontend/src/aws-exports.ts --region <region>` to regenerate
 *      this file with the deployed Cognito pool ID, client ID, and API URL.
 *   3. The generated file overwrites this stub — do not hand-edit either one;
 *      re-run the script instead.
 *
 * This file IS committed to the repository (it is not gitignored). Every
 * value still resolves through `import.meta.env.VITE_*` first, so real
 * secrets never need to live in source: set the VITE_* env vars at
 * build/deploy time (as the Docker Compose target does) instead of relying on
 * whatever literal is currently checked in here.
 */

const awsExports = {
  Auth: {
    Cognito: {
      // Cognito User Pool ID — replaced by generate_aws_exports.py at deploy time.
      userPoolId: import.meta.env.VITE_COGNITO_USER_POOL_ID ?? 'us-east-1_PLACEHOLDER',
      // Cognito App Client ID — replaced by generate_aws_exports.py at deploy time.
      userPoolClientId: import.meta.env.VITE_COGNITO_CLIENT_ID ?? 'PLACEHOLDER_CLIENT_ID',
      // Cognito hosted UI domain — replaced by generate_aws_exports.py at deploy time.
      loginWith: {
        oauth: {
          domain: import.meta.env.VITE_COGNITO_DOMAIN ?? 'contract-toaster-dev.auth.us-east-1.amazoncognito.com',
          scopes: ['email', 'openid', 'profile'],
          redirectSignIn: [import.meta.env.VITE_REDIRECT_SIGN_IN ?? 'http://localhost:3000'],
          redirectSignOut: [import.meta.env.VITE_REDIRECT_SIGN_OUT ?? 'http://localhost:3000'],
          responseType: 'code' as const,
        },
      },
    },
  },
};

// API base URL for the deployed App Runner service — replaced by
// generate_aws_exports.py at deploy time. Components read this via
// `import.meta.env.VITE_API_BASE_URL` directly (see PasswordLogin.tsx,
// ReviewSubmission.tsx, AdminUsers.tsx, AdminRetention.tsx, App.tsx); this
// export exists so the value is also discoverable from this file.
export const apiBaseUrl = import.meta.env.VITE_API_BASE_URL ?? '';

export default awsExports;
