import React from 'react';
import ReactDOM from 'react-dom/client';
import { Amplify } from 'aws-amplify';
// Global styles, load order matters:
//   1. Fonts (@fontsource/*, latin subset, weights 400/500/700) — must load
//      before any CSS that references --ct-font-* so the woff2s are
//      requested as early as possible.
//   2. tokens.css — our design-token vocabulary: surfaces, spacing, radii,
//      focus ring, motion, typography.
//   3. base.css — element base layer (typography, links, forms, buttons,
//      tables) on the --ct-* tokens.
//   4. app.css — app chrome (shell, tabs, header, chips) built on the tokens.
//   5. Amplify UI styles — primarily scopes the SSO Authenticator sign-in
//      screen, but this stylesheet also ships its own unscoped global reset
//      (e.g. `* { box-sizing: border-box }`); loaded last so its scoped
//      widget styling wins, but base.css owns the app's own box-sizing
//      reset rather than relying on this import for it.
// The strict Amplify-hosting CSP forbids remote CSS/fonts, so every one of
// these is bundled same-origin by Vite as real woff2/css files — no CDN
// links, no data: URIs. Each @fontsource import below pulls in only the
// latin subset for one weight (see docs/frontend-design-system.md §4.5).
import '@fontsource/space-grotesk/latin-500.css';
import '@fontsource/space-grotesk/latin-700.css';
import '@fontsource/instrument-sans/latin-400.css';
import '@fontsource/instrument-sans/latin-500.css';
import '@fontsource/instrument-sans/latin-700.css';
import '@fontsource/ibm-plex-mono/latin-400.css';
import './styles/tokens.css';
import './styles/base.css';
import './styles/app.css';
import '@aws-amplify/ui-react/styles.css';
import App from './App';
import awsExports from './aws-exports';
import { isPasswordMode } from './auth';

// Configure Amplify with the Cognito settings generated by `cdk deploy`.
// aws-exports.ts is committed with placeholder values; after a real deploy,
// `python3 scripts/generate_aws_exports.py --outputs <cdk-outputs.json>
// --output frontend/src/aws-exports.ts` overwrites it with the deployed
// Cognito pool ID, client ID, and API URL (see that script's module
// docstring for the full CDK-outputs key contract).
//
// For local development against a real deploy, run the command above with
// your dev CDK stack's outputs file. Otherwise the committed placeholder
// values (or VITE_* env var overrides) are used as-is.
//
// Docker Compose target (VITE_AUTH_MODE=password): there is no Cognito, so Amplify is not
// configured — the SPA uses username/password sign-in (PasswordLogin) instead.
if (!isPasswordMode()) {
  Amplify.configure(awsExports);
}

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
