import React from 'react';
import ReactDOM from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import App from './App';
import awsExports from './aws-exports';
import { isPasswordMode } from './auth';

// Configure Amplify with the Cognito settings generated by `cdk deploy`.
// aws-exports.ts is committed with placeholder values; after a real deploy,
// `python3 scripts/generate_aws_exports.py --outputs <cdk-outputs.json>
// --output frontend/src/aws-exports.ts` overwrites it with the deployed
// Cognito pool ID, client ID, and API URL (see that script's module
// docstring for the full CDK-outputs key contract).
//
// For local development against a real deploy, run the command above with
// your dev CDK stack's outputs file. Otherwise the committed placeholder
// values (or VITE_* env var overrides) are used as-is.
//
// DTS target (VITE_AUTH_MODE=password): there is no Cognito, so Amplify is not
// configured — the SPA uses username/password sign-in (PasswordLogin) instead.
if (!isPasswordMode()) {
  Amplify.configure(awsExports);
}

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
