#!/usr/bin/env python3
"""
Generate the SYNTHETIC placeholder standard-form .docx (issue #200).

## Problem this solves

There is no canonical standard-form .docx in the repo yet (see
standard-forms/README.md): the real EIAA form text is a GC deliverable, not
something engineering can fabricate. Without ANY real .docx, real-docx mode
(scripts/build_anchor_map.py --docx, scripts/diff_standard_form.py --docx)
is never exercised, and the §10 sub-clause-split loader logic added in issue
#200 has nothing to run against.

This script generates a clearly-labeled SYNTHETIC placeholder .docx --
standard-forms/eiaa-v1.0.0.SYNTHETIC.docx -- that faithfully expresses the
required *structure* of the real form (every registered section anchor,
including the §10 sub-clause split under a single "Miscellaneous" heading)
with short, generic, de-branded placeholder prose. It is NOT the real EIAA
standard-form text and must never be treated as one -- see
standard-forms/README.md.

When the real .docx is available, it replaces this file directly (same
filename convention swapped for a non-SYNTHETIC one, or this file is
deleted and the registry/CLI --docx flag points at the real file instead);
the loader/anchor-map/diff code added in issue #200 already works against
real OOXML and requires no code change.

## Heading text convention

Headings are typed WITHOUT a manually-typed leading section number (e.g.
"Admitting Students", not "1.2 Admitting Students") -- matching how a real
Word document using outline/multilevel-list auto-numbering linked to the
Heading styles renders: the visible "1.2" is generated by the numbering
definition, not stored in the paragraph's run text, so python-docx's
`paragraph.text` does not include it. A manually typed number in the
heading text (rather than real Word auto-numbering) would NOT match the
anchor map's plain heading strings -- see issue #200's "Required
verification" point 4. This fixture intentionally avoids that failure mode
by construction.

## §10 sub-clause split

`sec-2.2.1` ("Without Cause") is `absent_from_form` per
playbooks/eiaa-v1.0.0.sections.json and is deliberately OMITTED from this
document -- Exos's real form does not grant this right, and the anchor
exists in the map only so the coverage gate can flag a counterparty who
tries to introduce it.

Usage:
    python3 scripts/generate_synthetic_standard_form.py
    python3 scripts/generate_synthetic_standard_form.py --output <path>
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = REPO_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import build_anchor_map as bam  # noqa: E402
import playbook_registry  # noqa: E402

DEFAULT_OUTPUT = (
    REPO_ROOT / "standard-forms" / "eiaa-v1.0.0.SYNTHETIC.docx"
)

# Generic, de-branded placeholder body text per non-split anchor. This is
# NOT the real EIAA clause text -- short, structurally faithful placeholder
# prose only. "your"/"you" voicing (never "Exos"/"EXOS"), per the release
# de-brand convention.
BODY_TEXT = {
    "sec-preamble": (
        "This agreement is entered into by the parties identified in the "
        "signature block below."
    ),
    "sec-signature": (
        "The parties have executed this agreement as of the date set forth "
        "below."
    ),
    "sec-1": (
        "This section describes the student training program operated "
        "under this agreement."
    ),
    "sec-1.1": (
        "Each party shall perform its obligations under this section in "
        "good faith."
    ),
    "sec-1.2": (
        "Students are admitted to the program at your sole discretion, in "
        "accordance with your published admission criteria."
    ),
    "sec-1.3": (
        "You may inspect the training site upon reasonable prior notice."
    ),
    "sec-1.4": (
        "You may expel a student from the program for cause, upon written "
        "notice."
    ),
    "sec-1.5": (
        "Students receive no remuneration for participation in the "
        "program."
    ),
    "sec-1.6": (
        "Students are not eligible for insurance or other employee "
        "benefits through your organization."
    ),
    "sec-1.7": (
        "You retain final authority over all decisions regarding the "
        "program, including all matters of clinical care."
    ),
    "sec-2.1": (
        "This agreement remains in effect for the term stated in the "
        "signature block."
    ),
    "sec-2.2": (
        "This section describes how this agreement may be terminated."
    ),
    "sec-2.2.2": (
        "Either party may terminate this agreement for cause upon written "
        "notice of an uncured breach."
    ),
    "sec-2.3": (
        "Upon termination, each party shall return the other party's "
        "confidential information."
    ),
    "sec-3": (
        "Each party shall comply with all applicable laws and regulations "
        "in performing this agreement."
    ),
    "sec-4": (
        "Neither party shall discriminate against any individual on a "
        "protected basis."
    ),
    "sec-5": (
        "Student records shall be maintained and disclosed only as "
        "permitted by applicable law."
    ),
    "sec-6": (
        "Each party shall comply with applicable health-information "
        "privacy law where relevant, and neither party is a business "
        "associate of the other under that law."
    ),
    "sec-7": (
        "Each party shall keep the other party's confidential information "
        "confidential."
    ),
    "sec-8": (
        "Neither party shall be liable to the other for consequential "
        "damages, and each party's aggregate liability under this "
        "agreement shall not exceed $150,000."
    ),
    "sec-9": (
        "This agreement may be assigned to a party's operating entity "
        "without the other party's consent."
    ),
}

# §10 sub-clause body text, keyed by anchor, each led by the lettered
# marker registered in playbooks/eiaa-v1.0.0.sections.json's
# sub_clause_splits.sec-10.splits.
SEC_10_SPLIT_BODY = {
    "sec-10-notices": (
        "(a) Notices under this agreement must be delivered in writing to "
        "the address specified in the signature block."
    ),
    "sec-10-non-exclusive": (
        "(b) This agreement is non-exclusive; each party may enter similar "
        "agreements with other parties."
    ),
    "sec-10-merger": (
        "(c) This agreement, together with its exhibits, constitutes the "
        "entire agreement between the parties and may be amended only in a "
        "signed writing executed by both parties."
    ),
    "sec-10-precedence": (
        "(d) In the event of a conflict between this agreement and any "
        "exhibit, the terms of this agreement shall prevail."
    ),
}


def build_document(playbook_id: str = playbook_registry.DEFAULT_PLAYBOOK_ID):
    try:
        from docx import Document  # type: ignore
    except ImportError:
        print(
            "ERROR: python-docx is required to generate the synthetic "
            "standard form.\n  pip install python-docx",
            file=sys.stderr,
        )
        sys.exit(1)

    section_config = bam.load_section_config(playbook_id)
    config = section_config["sections"]
    absent_from_form_anchors = section_config["absent_from_form_anchors"]
    sub_clause_splits = section_config["sub_clause_splits"]

    doc = Document()
    # Plain (non-Heading-style) front-matter paragraphs -- deliberately NOT
    # `add_heading()` so they are inert with respect to the loader's
    # heading-matching logic (they match no anchor and are simply discarded
    # as unattached pre-first-section text, with no WARNING noise from a
    # heading-style paragraph matching nothing).
    doc.add_paragraph("EIAA Standard Form (SYNTHETIC placeholder — issue #200)")
    doc.add_paragraph(
        "This document is a SYNTHETIC engineering placeholder, not the real "
        "EIAA standard-form text. See standard-forms/README.md."
    )

    emitted_parents = set()

    for anchor, heading, sub_split, parent in config:
        if anchor in absent_from_form_anchors:
            # Deliberately absent from the real form -- omit entirely (see
            # module docstring).
            continue

        if sub_split:
            if parent in emitted_parents:
                continue
            group = sub_clause_splits[parent]
            doc.add_heading(group["source_heading"], level=2)
            for split in group["splits"]:
                body = SEC_10_SPLIT_BODY.get(split["anchor"])
                if body is None:
                    raise KeyError(
                        f"No SEC_10_SPLIT_BODY placeholder text for anchor "
                        f"{split['anchor']!r}"
                    )
                doc.add_paragraph(body)
            emitted_parents.add(parent)
            continue

        doc.add_heading(heading, level=2)
        body = BODY_TEXT.get(anchor)
        if body is None:
            raise KeyError(f"No BODY_TEXT placeholder text for anchor {anchor!r}")
        doc.add_paragraph(body)

    return doc


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the SYNTHETIC placeholder standard-form .docx (issue #200)."
    )
    parser.add_argument(
        "--playbook-id",
        type=str,
        default=playbook_registry.DEFAULT_PLAYBOOK_ID,
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    doc = build_document(args.playbook_id)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(args.output))
    print(f"Wrote SYNTHETIC placeholder standard form to: {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
