#!/usr/bin/env python3
"""
Mechanically derive one synthetic planted-violation gold fixture per
hard_rejection rule in playbooks/eiaa-v1.0.0.json that does not yet have
gold-case detector coverage — issue #62 item 5.

Per the #62 scope decision: "A mechanically-derived subset of the gold
set: one synthetic 'planted violation' case per existing hard_rejection
rule ... generated by script -- this restates the playbook's own
already-authored rules as test fixtures, not a new legal judgment call."

This script is idempotent and additive only: it never overwrites or
deletes an existing fixture file (so hand-authored fixtures like
reject-one-way-exos-indemnify.json are left untouched), and it only
generates a fixture for a rule that scripts/eval_harness.py's
missing_rule_coverage() reports as uncovered.

For each uncovered rule:
  - kind == "on_insert": derive a minimal `inserted_hunk` that contains
    exactly one trigger_term (the first, deterministically) and no
    exempt_terms, placed in the rule's first applies_to_topics entry.
  - kind == "on_remove_or_alter": derive an `altered_hunk` that OMITS all
    of protects.required_tokens (the token-removal violation the rule
    exists to catch), replacing the protected clause with innocuous
    boilerplate that does not accidentally satisfy any other rule's
    trigger_terms.

Every generated fixture sets "provenance": "synthetic" (no de-identification
sign-off required per docs/evaluation.md -> "De-identification standard")
and "generated_by": "scripts/generate_gold_fixtures.py" for traceability.

Usage:
    python3 scripts/generate_gold_fixtures.py           # write missing fixtures
    python3 scripts/generate_gold_fixtures.py --dry-run # print, don't write
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = REPO_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from eval_harness import (  # noqa: E402
    FIXTURES_PATH,
    PLAYBOOK_PATH,
    load_playbook,
    missing_rule_coverage,
)

# Innocuous replacement boilerplate used when generating an on_remove_or_alter
# violation: it must NOT contain any other rule's trigger_terms/required_tokens,
# so it doesn't accidentally plant a second, unintended violation.
_SAFE_REPLACEMENT_TEXT = (
    "The parties will address this subject in accordance with the terms "
    "otherwise set forth in this Agreement."
)


def _first_topic_id(rule: dict[str, Any]) -> str:
    applies_to = rule.get("applies_to_topics") or []
    if not applies_to:
        raise ValueError(f"rule {rule.get('id')!r} has no applies_to_topics")
    return applies_to[0]


def _derive_on_insert_case(
    rule: dict[str, Any], topics_by_id: dict[str, dict[str, Any]]
) -> dict[str, Any]:
    trigger_terms = rule.get("trigger_terms", [])
    if not trigger_terms:
        raise ValueError(f"on_insert rule {rule['id']!r} has no trigger_terms")
    match_type = rule.get("match", "word_boundary")
    # Issue #218: prefer the LONGEST plain trigger_term rather than
    # trigger_terms[0]. A rule's vocabulary mixes bare technical words
    # ('uncapped') with realistic drafter phrasings ('shall not be
    # limited', 'no cap on liability'); the longest entry is reliably the
    # fuller phrase, which reads as plausible clause language instead of a
    # single dangling word. Only meaningful for match_type != 'regex' --
    # regex-only rules (e.g. no-exos-indemnity) already have hand-authored
    # fixtures and don't reach this generator.
    term = max(trigger_terms, key=len)
    topic_id = _first_topic_id(rule)

    if match_type == "regex":
        # Build a minimal literal string that satisfies common patterns
        # used in this playbook (modal + volitional phrasing before
        # "indemnif..."). This generator only needs to reach rules with
        # no existing coverage; no-exos-indemnity already has hand
        # fixtures, so this branch is a safety fallback, not the primary
        # path exercised today.
        sample_hunk = (
            f"The parties agree to add a new provision under this section "
            f"reflecting the following language for testing purposes: "
            f"'{term}'."
        )
    else:
        # Issue #218: the prior template ("...this Agreement shall include
        # uncapped as a material term of this section.") forced an
        # arbitrary trigger term into noun position, which reads as
        # nonsense for adjectives/verb-phrase terms ('uncapped', 'shall
        # not be limited') and is exactly the "mechanically generated
        # single-sentence template" defect flagged in issue #218. Framing
        # the term as quoted clause language being added to the section is
        # grammatical regardless of the term's part of speech.
        sample_hunk = (
            f"The parties agree to add the following clause language to "
            f"this section of the Agreement: '{term}'."
        )

    topic = topics_by_id.get(topic_id)
    if topic is None:
        raise ValueError(
            f"topic {topic_id!r} (from rule {rule['id']!r}'s applies_to_topics) "
            "not found in playbook topics"
        )
    # Issue #218: use the topic's own section_ref (a real section label,
    # e.g. '8 Limitation on Liability', or '[absent] X' for a
    # not_in_standard topic) instead of the rule's DESCRIPTION sentence --
    # a rule description ('Counterparty introduces uncapped/unlimited
    # liability.') is not a section reference and was the fixture-realism
    # bug this issue fixes.
    section_ref = topic.get("section_ref", "")

    case_id = f"reject-{rule['id']}"
    return {
        "case_id": case_id,
        "description": (
            f"Mechanically-derived D2 planted case (scripts/generate_gold_fixtures.py) "
            f"for hard_rejection rule {rule['id']!r}: counterparty inserts language "
            f"containing the trigger term {term!r} into the {topic_id!r} topic. "
            f"Must fire {rule['id']} and result in REQUEST_CHANGE."
        ),
        "playbook_version": "1.0.0",
        "expected_decision": "REQUEST_CHANGE",
        "expected_issues": [
            {
                "playbook_topic_id": topic_id,
                "section_ref": section_ref,
                "is_hard_rejection": True,
                "rule_id": rule["id"],
            }
        ],
        "must_not_flag": [],
        "fp_tolerance": 0,
        "redline_checks": [],
        "planted_variation": {
            "topic_id": topic_id,
            "inserted_hunk": sample_hunk,
            "notes": (
                f"Mechanically generated: contains trigger_term {term!r} "
                f"(match={match_type}) for rule {rule['id']!r}."
            ),
        },
        "detector_expectation": {
            "rule_id": rule["id"],
            "expected_result": "fire",
            "rationale": (
                f"Inserted hunk contains trigger_term {term!r}, which is not in "
                f"{rule.get('exempt_terms', [])!r}; must fire {rule['id']!r}."
            ),
        },
        "provenance": "synthetic",
        "generated_by": "scripts/generate_gold_fixtures.py",
    }


def _sibling_required_tokens(rule: dict[str, Any], all_rules: list[dict[str, Any]]) -> list[str]:
    """required_tokens belonging to OTHER on_remove_or_alter rules that share
    an applies_to_topics entry with `rule`. These must be preserved verbatim
    in the generated altered_hunk so planting this rule's violation does not
    also accidentally strip a sibling rule's protected language and produce
    an unintended second fire (e.g. preserve-liability-cap and
    preserve-consequential-damages-waiver both live under
    limitation-of-liability / sec-8)."""
    my_topics = set(rule.get("applies_to_topics") or [])
    tokens: list[str] = []
    for other in all_rules:
        if other["id"] == rule["id"] or other.get("kind") != "on_remove_or_alter":
            continue
        other_topics = set(other.get("applies_to_topics") or [])
        if my_topics & other_topics:
            tokens.extend(other.get("protects", {}).get("required_tokens", []))
    return tokens


def _derive_on_remove_or_alter_case(
    rule: dict[str, Any], all_rules: list[dict[str, Any]] | None = None
) -> dict[str, Any]:
    protects = rule.get("protects", {})
    required_tokens = protects.get("required_tokens", [])
    if not required_tokens:
        raise ValueError(f"on_remove_or_alter rule {rule['id']!r} has no required_tokens")
    topic_id = _first_topic_id(rule)

    sibling_tokens = _sibling_required_tokens(rule, all_rules or [rule])
    preserved_clause = (
        f" This section otherwise continues to state: {'; '.join(sibling_tokens)}."
        if sibling_tokens
        else ""
    )
    replacement_text = _SAFE_REPLACEMENT_TEXT + preserved_clause

    case_id = f"reject-{rule['id']}"
    return {
        "case_id": case_id,
        "description": (
            f"Mechanically-derived D2 planted case (scripts/generate_gold_fixtures.py) "
            f"for hard_rejection rule {rule['id']!r}: counterparty removes/alters the "
            f"protected clause in {protects.get('section_anchor')!r}, deleting all of "
            f"required_tokens {required_tokens!r}. Must fire {rule['id']} and result "
            f"in REQUEST_CHANGE."
        ),
        "playbook_version": "1.0.0",
        "expected_decision": "REQUEST_CHANGE",
        "expected_issues": [
            {
                "playbook_topic_id": topic_id,
                "section_ref": protects.get("section_anchor", ""),
                "is_hard_rejection": True,
                "rule_id": rule["id"],
            }
        ],
        "must_not_flag": [],
        "fp_tolerance": 0,
        "redline_checks": [],
        "planted_variation": {
            "topic_id": topic_id,
            "altered_hunk": replacement_text,
            "notes": (
                f"Mechanically generated: replacement text omits all of "
                f"required_tokens {required_tokens!r} for rule {rule['id']!r} "
                f"(token_policy={protects.get('token_policy', 'any')!r}) while "
                f"verbatim-preserving sibling required_tokens {sibling_tokens!r} "
                f"so no other rule sharing this topic is unintentionally tripped."
            ),
        },
        "detector_expectation": {
            "rule_id": rule["id"],
            "expected_result": "fire",
            "rationale": (
                f"Replacement text contains none of required_tokens "
                f"{required_tokens!r}; must fire {rule['id']!r} under "
                f"token_policy={protects.get('token_policy', 'any')!r}."
            ),
        },
        "provenance": "synthetic",
        "generated_by": "scripts/generate_gold_fixtures.py",
    }


def derive_fixture(
    rule: dict[str, Any],
    all_rules: list[dict[str, Any]] | None = None,
    topics_by_id: dict[str, dict[str, Any]] | None = None,
) -> dict[str, Any]:
    if rule.get("kind") == "on_insert":
        return _derive_on_insert_case(rule, topics_by_id or {})
    if rule.get("kind") == "on_remove_or_alter":
        return _derive_on_remove_or_alter_case(rule, all_rules)
    raise ValueError(f"unrecognized hard_rejection kind: {rule.get('kind')!r}")


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    dry_run = "--dry-run" in argv

    playbook = load_playbook(PLAYBOOK_PATH)
    rules_by_id = {r["id"]: r for r in playbook.get("hard_rejections", [])}
    topics_by_id = {t["id"]: t for t in playbook.get("topics", [])}
    missing = missing_rule_coverage(FIXTURES_PATH, PLAYBOOK_PATH)

    if not missing:
        print("No missing per-rule gold-case coverage; nothing to generate.")
        return 0

    all_rules = list(rules_by_id.values())
    written = []
    for rule_id in missing:
        rule = rules_by_id[rule_id]
        fixture = derive_fixture(rule, all_rules, topics_by_id)
        out_path = FIXTURES_PATH / f"{fixture['case_id']}.json"
        if out_path.exists():
            # Additive-only: never overwrite an existing (possibly
            # hand-authored) fixture even if the rule was reported missing
            # due to a naming mismatch.
            print(f"SKIP (already exists): {out_path.name}")
            continue
        content = json.dumps(fixture, indent=2, sort_keys=False) + "\n"
        if dry_run:
            print(f"--- would write {out_path.name} ---")
            print(content)
        else:
            out_path.write_text(content, encoding="utf-8")
            print(f"WROTE {out_path.name}")
        written.append(out_path.name)

    print(f"\n{'Would generate' if dry_run else 'Generated'} {len(written)} fixture(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
